// Chippie Knowledge Pack Generator
// Compiles docs/*.md into src/data/chippieKnowledge.ts — a sectioned, keyword-indexed
// knowledge pack consumed server-side by the /api/chippie search_docs tool.
//
// Usage: node scripts/generateChippieKnowledge.mjs
// The generated file is committed so builds never depend on this script.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import console from 'node:console';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS_DIR = join(ROOT, 'docs');
const OUT_FILE = join(ROOT, 'src', 'data', 'chippieKnowledge.ts');

const MAX_SECTION_CHARS = 2800;

const STOPWORDS = new Set([
  'the', 'and', 'for', 'with', 'that', 'this', 'from', 'are', 'was', 'were',
  'has', 'have', 'had', 'not', 'its', 'can', 'all', 'you', 'your', 'our',
  'their', 'they', 'them', 'when', 'what', 'how', 'why', 'who', 'will',
  'shall', 'must', 'may', 'each', 'any', 'per', 'via', 'into', 'onto',
  'over', 'under', 'about', 'between', 'these', 'those', 'than', 'then',
  'but', 'use', 'used', 'using', 'also', 'been', 'being', 'more', 'most',
]);

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function extractKeywords(title, content) {
  const counts = new Map();
  const add = (word, weight) => {
    const w = word.toLowerCase();
    if (w.length < 3 || STOPWORDS.has(w) || /^\d+$/.test(w)) return;
    counts.set(w, (counts.get(w) ?? 0) + weight);
  };
  for (const w of title.split(/[^A-Za-z0-9]+/)) add(w, 10);
  for (const w of content.split(/[^A-Za-z0-9]+/)) add(w, 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 12)
    .map(([w]) => w);
}

function splitSections(source, markdown) {
  const lines = markdown.split(/\r?\n/);
  const sections = [];
  let title = 'Overview';
  let buffer = [];

  const flush = () => {
    const content = buffer.join('\n').trim();
    if (content.length > 40) sections.push({ source, title, content });
    buffer = [];
  };

  for (const line of lines) {
    const h = line.match(/^#{1,3}\s+(.+)/);
    if (h) {
      flush();
      title = h[1].replace(/[#*`]/g, '').trim();
    } else {
      buffer.push(line);
    }
  }
  flush();
  return sections;
}

const files = readdirSync(DOCS_DIR)
  .filter((f) => f.endsWith('.md'))
  .sort();

const sections = [];
for (const file of files) {
  const markdown = readFileSync(join(DOCS_DIR, file), 'utf8');
  for (const raw of splitSections(file, markdown)) {
    const content =
      raw.content.length > MAX_SECTION_CHARS
        ? raw.content.slice(0, MAX_SECTION_CHARS) + '\n[...section truncated]'
        : raw.content;
    sections.push({
      id: `${slugify(file.replace(/\.md$/, ''))}--${slugify(raw.title)}`,
      source: raw.source,
      title: raw.title,
      keywords: extractKeywords(raw.title, content),
      content,
    });
  }
}

// De-duplicate ids (repeated headings across a doc)
const seen = new Map();
for (const s of sections) {
  const n = seen.get(s.id) ?? 0;
  seen.set(s.id, n + 1);
  if (n > 0) s.id = `${s.id}-${n + 1}`;
}

const banner = `// AUTO-GENERATED by scripts/generateChippieKnowledge.mjs — do not edit by hand.
// Regenerate with: node scripts/generateChippieKnowledge.mjs
// Source: docs/*.md (${files.length} files, ${sections.length} sections)
// Consumed server-side by api/chippie.ts (search_docs tool). Do NOT import in client code.
`;

const body = `${banner}
export interface KnowledgeSection {
  id: string;
  source: string;
  title: string;
  keywords: string[];
  content: string;
}

export const CHIPPIE_KNOWLEDGE: KnowledgeSection[] = ${JSON.stringify(sections, null, 2)};
`;

writeFileSync(OUT_FILE, body, 'utf8');
console.log(`Wrote ${sections.length} sections from ${files.length} docs -> ${OUT_FILE}`);
