use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildInput {
    pub process_node: String,
    pub die_area: f64,
    pub die_width: f64,
    pub die_height: f64,
    pub transistor_count: f64,
    pub tdp: f64,
    pub topology: String,
    pub chiplet_count: u32,
    pub io_die_area: f64,
    pub defect_density: f64,
    pub wafer_starts_per_month: u32,
    pub packaging_cost: f64,
    pub test_time_seconds: f64,
    pub test_cost_per_second: f64,
    pub packaging_yield: f64,
    pub test_yield: f64,
    pub wafer_cost: f64,
    pub nre_cost: f64,
    pub asp: f64,
    pub target_volume: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComputedOutput {
    pub total_die_area: f64,
    pub transistor_density: f64,
    pub tdp_power_density: f64,
    pub die_yield: f64,
    pub dpw: u32,
    pub wafer_utilization: f64,
    pub raw_die_cost: f64,
    pub packaging_and_testing_cost: f64,
    pub gross_cost_per_good_die: f64,
    pub amortized_nre_cost: f64,
    pub fully_loaded_cost_per_die: f64,
    pub gross_margin: f64,
    pub operating_margin: f64,
    pub monthly_volume_million: f64,
    pub annual_volume_million: f64,
    pub lifetime_revenue_million: f64,
    pub lifetime_cogs_million: f64,
    pub lifetime_gross_profit_million: f64,
    pub lifetime_net_profit_million: f64,
    pub break_even_volume_million: f64,
    pub roi: f64,
}
